databases:
  - name: food-delivery-db
    databaseName: food_delivery
    user: food_delivery_user
    plan: free
    region: singapore

services:
  - type: web
    name: food-delivery-api
    env: docker
    region: singapore
    plan: free
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: food-delivery-db
          property: connectionString
      - key: PORT
        value: 8000
      - key: DB_NAME
        value: food_delivery
